# Generated by Django 4.0.1 on 2025-11-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=128, verbose_name='序号')),
                ('chinese', models.CharField(max_length=32, verbose_name='汉语')),
                ('english', models.CharField(max_length=32, verbose_name='英语')),
                ('swahili', models.CharField(max_length=32, verbose_name='斯语')),
                ('xieyin', models.CharField(max_length=32, verbose_name='汉语谐音')),
                ('portrait', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片')),
                ('fayin', models.FileField(blank=True, null=True, upload_to='', verbose_name='音频发音')),
                ('isDraft', models.BooleanField(default=True, verbose_name='是否手稿')),
                ('readNum', models.IntegerField(default=0, verbose_name='阅读量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '词条信息',
                'verbose_name_plural': '词条信息',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Leixing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型列表')),
            ],
            options={
                'verbose_name': '所属类型（单词，短语，视频）',
                'verbose_name_plural': '所属类型（单词，短语，视频）',
            },
        ),
        migrations.CreateModel(
            name='Lingyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='领域名称')),
                ('img', models.ImageField(default='', upload_to='lingyulogo', verbose_name='图标')),
                ('leixing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lingyu', to='web.leixing', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '领域范围',
                'verbose_name_plural': '领域范围',
            },
        ),
        migrations.CreateModel(
            name='NoticeBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
            ],
            options={
                'verbose_name': '喇叭公告',
                'verbose_name_plural': '喇叭公告',
            },
        ),
        migrations.CreateModel(
            name='Sublingyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='子领域名称')),
                ('lingyu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublingyu', to='web.lingyu', verbose_name='所属主领域')),
            ],
            options={
                'verbose_name': '子领域范围',
                'verbose_name_plural': '子领域范围',
            },
        ),
        migrations.CreateModel(
            name='MyFavoritAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ctitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem', verbose_name='条目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfavoritad', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '词条收藏',
                'verbose_name_plural': '词条收藏',
            },
        ),
        migrations.CreateModel(
            name='ImgManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ctportrait', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ctitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctportrait', to='web.ctitem', verbose_name='所属词条')),
            ],
            options={
                'verbose_name': '词条图片',
                'verbose_name_plural': '词条图片',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='ctitem',
            name='lingyu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctitem', to='web.sublingyu', verbose_name='所属领域'),
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('img', models.ImageField(upload_to='swiper', verbose_name='图片')),
                ('leixing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.leixing', verbose_name='国家')),
            ],
            options={
                'verbose_name': '封面轮播',
                'verbose_name_plural': '封面轮播',
            },
        ),
    ]
