# Generated by Django 4.0.1 on 2025-11-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctitem',
            old_name='index',
            new_name='xuhao',
        ),
    ]
