# Generated by Django 4.0.1 on 2025-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_index_ctitem_xuhao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctitem',
            name='xuhao',
        ),
        migrations.AddField(
            model_name='ctitem',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
