# Generated by Django 4.0.1 on 2025-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_ctitem_xuhao_ctitem_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctitem',
            name='isDraft',
        ),
        migrations.AddField(
            model_name='ctitem',
            name='status',
            field=models.CharField(choices=[('0', '手稿'), ('1', '已修改'), ('2', '已发布')], default='0', max_length=1, verbose_name='状态'),
        ),
    ]
