# Generated by Django 4.0.1 on 2025-11-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_ctitem_isdraft_ctitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='YinManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yin', models.FileField(upload_to='ctyinpin', verbose_name='音频')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ctitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctyinpin', to='web.ctitem', verbose_name='所属词条')),
            ],
            options={
                'verbose_name': '词条音频',
                'verbose_name_plural': '词条音频',
                'ordering': ['-create_time'],
            },
        ),
    ]
