# Generated by Django 4.0.1 on 2025-11-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_yinmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctitem',
            name='fayin',
        ),
        migrations.RemoveField(
            model_name='ctitem',
            name='portrait',
        ),
    ]
