# Generated by Django 4.0.1 on 2025-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_ctitem_fayin_remove_ctitem_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='fayin',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='音频发音'),
        ),
        migrations.AddField(
            model_name='ctitem',
            name='portrait',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='图片'),
        ),
    ]
