# Generated by Django 4.0.1 on 2025-11-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_ctitem_fayin_ctitem_portrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctitem',
            options={'ordering': ['create_time'], 'verbose_name': '词条信息', 'verbose_name_plural': '词条信息'},
        ),
    ]
