# Generated by Django 4.0.1 on 2025-11-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_ctitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='lingyu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctitem', to='web.sublingyu', verbose_name='所属领域'),
        ),
    ]
