# Generated by Django 4.0.1 on 2025-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_ctitem_lingyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublingyu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='subolingyulogo', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='lingyu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lingyulogo', verbose_name='图标'),
        ),
    ]
