# Generated by Django 4.0.1 on 2025-11-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_sublingyu_img_alter_lingyu_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lingyu',
            options={'ordering': ['index'], 'verbose_name': '领域范围', 'verbose_name_plural': '领域范围'},
        ),
        migrations.AlterModelOptions(
            name='sublingyu',
            options={'ordering': ['index'], 'verbose_name': '子领域范围', 'verbose_name_plural': '子领域范围'},
        ),
        migrations.AddField(
            model_name='lingyu',
            name='index',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='sublingyu',
            name='index',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
