# Generated by Django 4.0.1 on 2025-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_lingyu_options_alter_sublingyu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='chinese',
            field=models.CharField(max_length=64, verbose_name='汉语'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='english',
            field=models.CharField(max_length=64, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='swahili',
            field=models.CharField(max_length=64, verbose_name='斯语'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='xieyin',
            field=models.CharField(max_length=64, verbose_name='汉语谐音'),
        ),
        migrations.AlterField(
            model_name='sublingyu',
            name='name',
            field=models.CharField(max_length=64, verbose_name='子领域名称'),
        ),
    ]
