# Generated by Django 4.0.1 on 2025-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_ctitem_chinese_alter_ctitem_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='fayin',
            field=models.FileField(blank=True, null=True, upload_to='ctyinpin', verbose_name='音频发音'),
        ),
    ]
