# Generated by Django 4.0.1 on 2025-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_ctitem_fayin'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='index',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
        migrations.AddField(
            model_name='noticebar',
            name='index',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
