# Generated by Django 4.0.1 on 2025-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_carousel_index_noticebar_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['index'], 'verbose_name': '封面轮播', 'verbose_name_plural': '封面轮播'},
        ),
        migrations.AlterModelOptions(
            name='noticebar',
            options={'ordering': ['index'], 'verbose_name': '喇叭公告', 'verbose_name_plural': '喇叭公告'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='type',
            field=models.CharField(default='', max_length=32, verbose_name='标志'),
        ),
    ]
