# Generated by Django 4.0.1 on 2025-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_carousel_options_alter_noticebar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='word_or_phrase',
            field=models.CharField(choices=[('0', '单词'), ('1', '短语')], default='', max_length=1, verbose_name='单词还是短语'),
        ),
    ]
