# Generated by Django 4.0.1 on 2025-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_ctitem_word_or_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='isTuijian',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
