# Generated by Django 4.0.1 on 2025-11-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_ctitem_istuijian'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='recordername',
            field=models.CharField(default='', max_length=32, verbose_name='录制人'),
        ),
    ]
