# Generated by Django 4.0.1 on 2025-11-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_ctitem_recordername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctitem',
            old_name='recordername',
            new_name='recorderName',
        ),
    ]
