# Generated by Django 4.0.1 on 2025-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_rename_recordername_ctitem_recordername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='portrait',
            field=models.ImageField(default='ctportrait/zhanwei.jpg', max_length=256, upload_to='ctportrait', verbose_name='图片'),
        ),
    ]
