# Generated by Django 4.0.1 on 2025-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_ctitem_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='portrait',
            field=models.ImageField(blank=True, default='ctportrait/zhanwei.jpg', max_length=256, null=True, upload_to='ctportrait', verbose_name='图片'),
        ),
    ]
