# Generated by Django 4.0.1 on 2025-11-30 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0021_alter_ctitem_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscationManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='商品名称')),
                ('price', models.CharField(max_length=8, verbose_name='价格')),
                ('out_trade_no', models.CharField(max_length=128, verbose_name='自己系统单号')),
                ('transaction_id', models.CharField(default='', max_length=128, verbose_name='微信支付单号')),
                ('status', models.CharField(choices=[('0', '待支付'), ('1', '已支付')], default='0', max_length=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertranscation', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易管理 ',
                'verbose_name_plural': '交易管理 ',
            },
        ),
    ]
