# Generated by Django 4.0.1 on 2025-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_transcationmanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcationmanage',
            name='prepay_id',
            field=models.CharField(default='', max_length=64, verbose_name='微信预付订单'),
        ),
    ]
