# Generated by Django 4.0.1 on 2025-12-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_transcationmanage_prepay_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='定价')),
                ('points', models.IntegerField(verbose_name='积分数')),
            ],
            options={
                'verbose_name': '价目表 ',
                'verbose_name_plural': '价目表 ',
            },
        ),
    ]
