# Generated by Django 4.0.1 on 2025-11-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_pricelistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcationmanage',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
