# Generated by Django 4.0.1 on 2025-12-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctitem',
            name='recorderName',
        ),
    ]
