# Generated by Django 4.0.1 on 2025-12-01 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0027_remove_ctitem_recordername'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录制人'),
        ),
    ]
