# Generated by Django 4.0.1 on 2025-12-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_ctitem_recorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='sublingyu',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='序号'),
        ),
    ]
