# Generated by Django 4.0.1 on 2025-12-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_ctitem_index_alter_sublingyu_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='index',
            field=models.CharField(default=0, max_length=8, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='lingyu',
            name='index',
            field=models.CharField(default=0, max_length=8, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='sublingyu',
            name='index',
            field=models.CharField(default=0, max_length=8, verbose_name='序号'),
        ),
    ]
