# Generated by Django 4.0.1 on 2025-12-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_ctitem_index_alter_lingyu_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='leixing',
        ),
        migrations.RemoveField(
            model_name='lingyu',
            name='leixing',
        ),
        migrations.DeleteModel(
            name='Leixing',
        ),
    ]
