# Generated by Django 4.0.1 on 2025-12-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_remove_carousel_leixing_remove_lingyu_leixing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctitem',
            name='readNum',
        ),
    ]
