# Generated by Django 4.0.1 on 2025-12-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_remove_ctitem_readnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='isWrong',
            field=models.BooleanField(default=False, verbose_name='是否有错'),
        ),
    ]
