# Generated by Django 4.0.1 on 2025-12-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_ctitem_iswrong'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', '单词'), ('1', '短语')], max_length=1, verbose_name='类型')),
                ('amount', models.IntegerField(verbose_name='多少')),
            ],
            options={
                'verbose_name': '点数规则 ',
                'verbose_name_plural': '点数规则 ',
            },
        ),
    ]
