# Generated by Django 4.0.1 on 2025-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_pointrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='status',
            field=models.CharField(choices=[('0', '初始draft'), ('1', '未发布'), ('2', '已发布')], default='0', max_length=1, verbose_name='状态'),
        ),
    ]
