# Generated by Django 4.0.1 on 2025-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_ctitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointrule',
            options={'verbose_name': '点数消耗 ', 'verbose_name_plural': '点数消耗 '},
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='isWrong',
            field=models.BooleanField(default=False, verbose_name='反馈有错'),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='amount',
            field=models.IntegerField(verbose_name='消耗点数'),
        ),
    ]
