# Generated by Django 4.0.1 on 2025-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_pointrule_options_alter_ctitem_iswrong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistmodel',
            name='points',
            field=models.IntegerField(verbose_name='积分点数（个）'),
        ),
        migrations.AlterField(
            model_name='pricelistmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='定价（元）'),
        ),
    ]
