# Generated by Django 4.0.1 on 2025-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_pricelistmodel_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='index',
            field=models.CharField(default=0, max_length=8, verbose_name='编号'),
        ),
    ]
