# Generated by Django 4.0.1 on 2025-12-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_ctitem_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctitem',
            options={'ordering': ['-lingyu', 'index'], 'verbose_name': '词条信息', 'verbose_name_plural': '词条信息'},
        ),
    ]
