# Generated by Django 4.0.1 on 2025-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_ctitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='index',
            field=models.IntegerField(default=0, max_length=8, verbose_name='编号'),
        ),
    ]
