# Generated by Django 4.0.1 on 2025-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_ctitem_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='index',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
    ]
