# Generated by Django 4.0.1 on 2025-12-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0042_alter_ctitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='userquestionhistory',
            index=models.Index(fields=['user', 'question'], name='web_userque_user_id_c6259e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquestionhistory',
            unique_together={('user', 'question')},
        ),
    ]
