# Generated by Django 4.0.1 on 2025-12-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_userquestionhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionhistory',
            options={'verbose_name': '做过的题', 'verbose_name_plural': '做过的题'},
        ),
    ]
