# Generated by Django 4.0.1 on 2025-12-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0045_alter_userquestionhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavoritCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sublingyu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sublingyu', verbose_name='子领域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myfavoritcat', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '领域收藏',
                'verbose_name_plural': '领域收藏',
            },
        ),
    ]
