# Generated by Django 4.1 on 2025-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_myfavoritcat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfavoritcat',
            options={'verbose_name': '子领域收藏', 'verbose_name_plural': '子领域收藏'},
        ),
        migrations.AlterField(
            model_name='myfavoritad',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
