# Generated by Django 4.1 on 2025-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_myfavoritcat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavoritad',
            name='zz',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
