# Generated by Django 4.0.1 on 2025-12-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_myfavoritad_zz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfavoritad',
            name='zz',
        ),
    ]
