# Generated by Django 4.0.1 on 2025-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_remove_myfavoritad_zz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublingyu',
            name='isTiku',
            field=models.BooleanField(default=False, verbose_name='初始题库'),
        ),
    ]
