# Generated by Django 4.0.1 on 2025-12-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_sublingyu_istiku'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfavoritcat',
            name='favAllItem',
            field=models.BooleanField(default=False, verbose_name='收藏子类全部词条'),
        ),
    ]
