# Generated by Django 4.0.1 on 2025-12-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0051_myfavoritcat_favallitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=64, verbose_name='答案')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('ctitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem', verbose_name='词条')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户错题',
                'verbose_name_plural': '用户错题',
            },
        ),
    ]
