# Generated by Django 4.0.1 on 2025-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_mistakemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistakemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
