# Generated by Django 4.0.1 on 2025-12-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_alter_mistakemodel_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yinmanage',
            name='ctitem',
        ),
        migrations.DeleteModel(
            name='ImgManage',
        ),
        migrations.DeleteModel(
            name='YinManage',
        ),
    ]
