# Generated by Django 4.0.1 on 2025-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_remove_yinmanage_ctitem_delete_imgmanage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionhistory',
            name='action',
            field=models.CharField(blank=True, choices=[('0', '已记住'), ('1', '没记住')], max_length=1, null=True, verbose_name='是否记住'),
        ),
    ]
