# Generated by Django 4.0.1 on 2025-12-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_userquestionhistory_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuestionHistory',
        ),
    ]
