# Generated by Django 4.0.1 on 2025-12-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0056_delete_userquestionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('0', '已记住'), ('1', '没记住')], max_length=1, null=True, verbose_name='是否记住')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ctitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
