# Generated by Django 4.0.1 on 2025-12-12 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0057_usercardhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercardhistory',
            options={'verbose_name': '做过的题', 'verbose_name_plural': '做过的题'},
        ),
        migrations.AlterUniqueTogether(
            name='usercardhistory',
            unique_together={('user', 'ctitem')},
        ),
        migrations.AddIndex(
            model_name='usercardhistory',
            index=models.Index(fields=['user', 'ctitem'], name='web_usercar_user_id_1f9fcc_idx'),
        ),
    ]
