# Generated by Django 4.0.1 on 2025-12-12 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0058_alter_usercardhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercardhistory',
            name='web_usercar_user_id_1f9fcc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='usercardhistory',
            unique_together={('user', 'ctitem', 'action')},
        ),
        migrations.AddIndex(
            model_name='usercardhistory',
            index=models.Index(fields=['user', 'ctitem', 'action'], name='web_usercar_user_id_cbe02c_idx'),
        ),
    ]
