# Generated by Django 4.0.1 on 2025-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_remove_usercardhistory_web_usercar_user_id_1f9fcc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardhistory',
            name='action',
            field=models.CharField(blank=True, choices=[('0', '认识'), ('1', '不认识')], max_length=1, null=True, verbose_name='是否记住'),
        ),
    ]
