# Generated by Django 4.0.1 on 2025-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_usercardhistory_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceListModel',
        ),
        migrations.DeleteModel(
            name='TranscationManage',
        ),
    ]
