# Generated by Django 4.0.1 on 2025-12-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_delete_pricelistmodel_delete_transcationmanage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctitem',
            options={'ordering': ['-lingyu__index', 'xuhao'], 'verbose_name': '词条信息', 'verbose_name_plural': '词条信息'},
        ),
        migrations.RenameField(
            model_name='ctitem',
            old_name='index',
            new_name='xuhao',
        ),
    ]
