# Generated by Django 4.0.1 on 2025-12-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_alter_ctitem_options_rename_index_ctitem_xuhao'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistakemodel',
            name='isGongke',
            field=models.BooleanField(default=False, verbose_name='是否攻克'),
        ),
    ]
