# Generated by Django 4.0.1 on 2025-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_mistakemodel_isgongke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistakemodel',
            name='answers',
            field=models.CharField(max_length=64, verbose_name='错误答案'),
        ),
    ]
