# Generated by Django 4.0.1 on 2025-12-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_alter_mistakemodel_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mistakemodel',
            options={'ordering': ['-create_time'], 'verbose_name': '用户错题', 'verbose_name_plural': '用户错题'},
        ),
    ]
