# Generated by Django 4.0.1 on 2025-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_alter_mistakemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='fayin2',
            field=models.FileField(blank=True, null=True, upload_to='ctyinpin2', verbose_name='发音2'),
        ),
        migrations.AddField(
            model_name='ctitem',
            name='fayin3',
            field=models.FileField(blank=True, null=True, upload_to='ctyinpin3', verbose_name='发音3'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='fayin',
            field=models.FileField(blank=True, null=True, upload_to='ctyinpin', verbose_name='发音1'),
        ),
    ]
