# Generated by Django 4.0.1 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_ctitem_fayin2_ctitem_fayin3_alter_ctitem_fayin'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('xuhao', models.IntegerField(verbose_name='序号')),
            ],
            options={
                'verbose_name': '知识库分类',
                'verbose_name_plural': '知识库分类',
            },
        ),
    ]
