# Generated by Django 4.0.1 on 2025-12-18 19:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_knowledgetypemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgetypemodel',
            options={'verbose_name': '知识分类', 'verbose_name_plural': '知识分类'},
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('portrait', models.ImageField(upload_to='article', verbose_name='封面图')),
                ('desp', models.CharField(max_length=128, verbose_name='概述')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('attach', models.FileField(blank=True, null=True, upload_to='', verbose_name='附件文档')),
                ('favnum', models.IntegerField(default=0, verbose_name='收藏数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='web.knowledgetypemodel')),
            ],
            options={
                'verbose_name': '知识文案',
                'verbose_name_plural': '知识文案',
            },
        ),
    ]
