# Generated by Django 4.0.1 on 2025-12-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_alter_knowledgetypemodel_options_articlemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
    ]
