# Generated by Django 4.0.1 on 2025-12-19 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0069_alter_articlemodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='portrait',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='desp',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='概述'),
            preserve_default=False,
        ),
    ]
