# Generated by Django 4.0.1 on 2025-12-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_rename_portrait_articlemodel_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='summary',
        ),
    ]
