# Generated by Django 4.0.1 on 2025-12-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_articlemodel_date_articlemodel_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='summary',
        ),
    ]
