# Generated by Django 4.0.1 on 2025-12-19 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_remove_articlemodel_date_remove_articlemodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='概述'),
            preserve_default=False,
        ),
    ]
