# Generated by Django 4.0.1 on 2025-12-19 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0074_articlemodel_date_articlemodel_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='话题')),
            ],
            options={
                'verbose_name': '话题分类',
                'verbose_name_plural': '话题分类',
            },
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32, verbose_name='话题')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertopic', to=settings.AUTH_USER_MODEL, verbose_name='发帖人')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typetopic', to='web.topictypemodel', verbose_name='话题')),
            ],
            options={
                'verbose_name': '社区话题',
                'verbose_name_plural': '社区话题',
            },
        ),
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorcomments', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.topicmodel')),
            ],
            options={
                'verbose_name': '话题评论',
                'verbose_name_plural': '话题评论',
            },
        ),
    ]
