# Generated by Django 4.0.1 on 2025-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0075_topictypemodel_topicmodel_topiccomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=models.CharField(max_length=32, verbose_name='话题'),
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
