# Generated by Django 4.0.1 on 2025-12-19 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0076_alter_topiccomment_content_alter_topicmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorcomments', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=models.CharField(max_length=32, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='topiccomment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.topicmodel', verbose_name='话题'),
        ),
    ]
