# Generated by Django 4.0.1 on 2025-12-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0077_alter_topiccomment_author_alter_topiccomment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='topicimg', verbose_name='图片')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppicimg', to='web.topicmodel', verbose_name='话题')),
            ],
            options={
                'verbose_name': '话题图片',
                'verbose_name_plural': '话题图片',
            },
        ),
    ]
