# Generated by Django 4.0.1 on 2025-12-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_topicimgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='标题'),
        ),
    ]
