# Generated by Django 4.0.1 on 2025-12-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0080_alter_topiccomment_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topictypemodel',
            old_name='type',
            new_name='name',
        ),
    ]
