# Generated by Django 4.0.1 on 2025-12-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0081_rename_type_topictypemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='tag',
            field=models.CharField(default='', max_length=32, verbose_name='tag标签'),
        ),
    ]
