# Generated by Django 4.0.1 on 2025-12-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_topiclikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicimgs',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppicimg', to='web.topicmodel', verbose_name='话题'),
        ),
    ]
