# Generated by Django 4.0.1 on 2025-12-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_alter_topicimgs_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'ordering': ['isTop', '-create_time'], 'verbose_name': '社区话题', 'verbose_name_plural': '社区话题'},
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='isTop',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
