# Generated by Django 4.0.1 on 2025-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0085_alter_topicmodel_options_topicmodel_istop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='tag标签'),
        ),
    ]
