# Generated by Django 4.0.1 on 2025-12-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0086_alter_topicmodel_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FayinTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='类型')),
                ('xuhao', models.CharField(max_length=8, verbose_name='标识')),
            ],
            options={
                'verbose_name': '发音种类',
                'verbose_name_plural': '发音种类',
            },
        ),
    ]
