# Generated by Django 4.0.1 on 2025-12-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0087_fayintypemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fayintypemodel',
            name='xuhao',
            field=models.CharField(default='', max_length=8, verbose_name='标识'),
        ),
    ]
