# Generated by Django 4.0.1 on 2025-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_alter_fayintypemodel_xuhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fayintypemodel',
            name='xuhao',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='标识'),
        ),
    ]
