# Generated by Django 4.0.1 on 2025-12-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0089_alter_fayintypemodel_xuhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=models.CharField(max_length=64, verbose_name='评论'),
        ),
    ]
