# Generated by Django 4.0.1 on 2025-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0090_alter_topiccomment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'ordering': ['-isTop', '-create_time'], 'verbose_name': '社区话题', 'verbose_name_plural': '社区话题'},
        ),
        migrations.AlterField(
            model_name='topicmodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='标题'),
        ),
    ]
