# Generated by Django 4.0.1 on 2025-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0091_alter_topicmodel_options_alter_topicmodel_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctitem',
            options={'ordering': ['lingyu__index', 'id'], 'verbose_name': '词条信息', 'verbose_name_plural': '词条信息'},
        ),
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'ordering': ['-isTop', 'create_time'], 'verbose_name': '社区话题', 'verbose_name_plural': '社区话题'},
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='fayin',
            field=models.FileField(blank=True, default=None, null=True, upload_to='ctyinpin', verbose_name='发音1'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='fayin2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='ctyinpin2', verbose_name='发音2'),
        ),
        migrations.AlterField(
            model_name='ctitem',
            name='fayin3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='ctyinpin3', verbose_name='发音3'),
        ),
    ]
