# Generated by Django 4.0.1 on 2025-12-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0092_alter_ctitem_options_alter_topicmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fayintypemodel',
            name='isTuijian',
            field=models.BooleanField(default=False, verbose_name='发音优先推荐'),
        ),
    ]
