# Generated by Django 4.0.1 on 2025-12-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0093_fayintypemodel_istuijian'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenPracticeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('0', '做错'), ('1', '做对')], max_length=1, null=True, verbose_name='正确与否')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ctitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem', verbose_name='词条')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listenpractice', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '听音练习记录',
                'verbose_name_plural': '听音练习记录',
                'ordering': ['-create_time'],
            },
        ),
    ]
