# Generated by Django 4.0.1 on 2026-01-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0094_listenpracticemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercardhistory',
            name='action',
            field=models.CharField(blank=True, choices=[('0', '认识'), ('1', '不认识')], db_index=True, max_length=1, null=True, verbose_name='是否记住'),
        ),
    ]
