# Generated by Django 4.0.1 on 2026-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0095_alter_usercardhistory_action'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='myfavoritad',
            index=models.Index(fields=['user'], name='user'),
        ),
    ]
