# Generated by Django 4.0.1 on 2026-01-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0096_myfavoritad_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='myfavoritad',
            index=models.Index(fields=['ctitem'], name='ctitem'),
        ),
    ]
