# Generated by Django 4.0.1 on 2026-01-06 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0097_myfavoritad_ctitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录制时间')),
                ('ctitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ctitem', verbose_name='词条')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='录制人')),
            ],
            options={
                'verbose_name': '录制记录',
                'verbose_name_plural': '录制记录',
            },
        ),
    ]
