# Generated by Django 4.0.1 on 2026-01-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0098_userrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctitem',
            old_name='fayin',
            new_name='fayin1',
        ),
    ]
