# Generated by Django 4.0.1 on 2026-01-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0099_rename_fayin_ctitem_fayin1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctitem',
            old_name='fayin1',
            new_name='siyufayin1',
        ),
        migrations.RenameField(
            model_name='ctitem',
            old_name='fayin2',
            new_name='siyufayin2',
        ),
        migrations.RenameField(
            model_name='ctitem',
            old_name='fayin3',
            new_name='siyufayin3',
        ),
    ]
