# Generated by Django 4.0.1 on 2026-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0100_rename_fayin1_ctitem_siyufayin1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctitem',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误日志'),
        ),
        migrations.AddField(
            model_name='ctitem',
            name='generation_status',
            field=models.CharField(choices=[('pending', '等待生成'), ('processing', '生成中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='生成状态'),
        ),
    ]
