# Generated by Django 4.0.1 on 2026-01-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0101_ctitem_error_message_ctitem_generation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctitem',
            name='swahili',
            field=models.CharField(max_length=64, verbose_name='葡语'),
        ),
    ]
