"""
Django settings for tantansiyu project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8vo-ms15o@e0o@@tp!h2yhqo&acibex0(gbx_a#4s*5-1=w*u6'
AES_SECRET_KEY = 'Qq1788fghjm249ap'  # 必须是 16, 24 或 32 字节长度


if platform.system() in ["Windows", "Darwin"]:
    DEBUG = True
    DOMAIN = 'http://127.0.0.1:8000'
    STATICFILES_DIRS = [
        BASE_DIR.joinpath("static"),
    ]
    NOTICE_DEV_PRO = 'developer'  # 小程序通知时是开发还是正式 模式
else:
    DEBUG = False   # 正式环境，关闭debug
    DOMAIN = 'https://siyu.jsxinlingdi.com'
    STATIC_ROOT = BASE_DIR.joinpath('static')
    NOTICE_DEV_PRO = 'formal'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://siyu.jsxinlingdi.com', ]
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'drf_multiple_model',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'corsheaders',
    'rest_framework',
    'myuser',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tantansiyu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tantansiyu.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'angepuyu' if platform.system() in ["Windows", "Darwin"] else 'angepuyu',
        'USER': 'root' if platform.system() in ["Windows", "Darwin"] else 'angepuyu',
        'PASSWORD': 'qq1788lover',
        'HOST': '127.0.0.1',
        # 'HOST': '43.165.63.29',
        'PORT': 3306,
        'OPTIONS': {  # 解决昵称含有特殊字符
            'charset': 'utf8mb4'
        }
    }
}

# 将 10240 替换为你需要的、足够大的数字[citation:1]
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

IMPORT_EXPORT_USE_TRANSACTIONS = True

LANGUAGE_CODE = 'zh-hans'  # 'en-us'

TIME_ZONE = 'Asia/Shanghai'  # 'UTC'

USE_I18N = True

USE_TZ = True

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
# admin后台显示时间格式
DATETIME_FORMAT = 'Y-m-d H:i'
DATE_FORMAT = 'Y-m-d'

# USE_L10N = True # 默认False，以本地化格式显示数字和时间

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.joinpath("media")

# CKEDITOR上传目录
CKEDITOR_UPLOAD_PATH = 'upload/'
CKEDITOR_IMAGE_BACKEND = 'pillow'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS配置
CORS_ORIGIN_ALLOW_ALL = True

# 用户模型
AUTH_USER_MODEL = 'myuser.UserProfile'

SIMPLEUI_HOME_INFO = False  # simpleUI广告
SIMPLEUI_HOME_QUICK = True  # 首页快捷操作
SIMPLEUI_HOME_ACTION = False  # 最近动作，也关闭
SIMPLEUI_ANALYSIS = False  # 关闭隐藏的js追踪使用分析

# SIMPLEUI_HOME_TITLE = '淮安统计数据'  # 【首页】按钮文案配置
# SIMPLEUI_HOME_PAGE = '/user/huaian_dashboard/'  # 可用于嵌入其他链接，这里可以直接方便的嵌入报表链接
# SIMPLEUI_HOME_ICON = 'el el-icon-platform-eleme'

# 去掉默认Logo或换成自己Logo链接
SIMPLEUI_LOGO = '/static/logo.jpg'

SIMPLEUI_LOGIN_PARTICLES = False

# simpleUI 后台风格样式
SIMPLEUI_DEFAULT_THEME = 'light.css'  # 'e-green.css'  # 'admin.lte.css'

# 离线模式，从本地加载静态资源，否则远程cdn
SIMPLEUI_STATIC_OFFLINE = True

REST_FRAMEWORK = {
    # 'DEFAULT_THROTTLE_RATES': {
    #     'user': '10/d',
    #     'anon': '3/m',
    # },

    # 没必要
    # 'PAGE_SIZE': 3,
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination'

    # 加密解析器和渲染器
    # 'DEFAULT_PARSER_CLASSES': [
    #     'utils.parsers.DecryptJSONParser'
    # ],
    # 'DEFAULT_RENDERER_CLASSES': [
    #     'utils.renderers.EncryptJSONRenderer'
    # ],
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 后台菜单设置
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,
    'dynamic': False,
    'menus': [
        {
            'app': 'myuser',
            'name': '用户管理',
            'icon': 'fas fa-user',
            'models': [
                {
                    'name': '我的用户',
                    'icon': 'fa fa-user',
                    'url': 'myuser/userprofile/'
                },
                {
                    'name': '用户登录',
                    'icon': 'fa fa-user',
                    'url': 'myuser/userloginrecordmodel/'
                },
                {
                    'name': '购买套餐',
                    'icon': 'fa fa-user',
                    'url': 'myuser/huiyuantype/'
                },
                {
                    'name': '购买记录',
                    'icon': 'fa fa-user',
                    'url': 'myuser/transcationmanage/'
                },
                {
                    'name': '做题得分',
                    'icon': 'fa fa-user',
                    'url': 'myuser/scorerecordmodel/'
                },
                {
                    'name': '录音统计',
                    'icon': 'fa fa-user',
                    'url': 'web/userrecord/'
                },
            ]
        },
        {
            'app': 'web',
            'name': '数据管理',
            'icon': 'fas fa-database',
            'models': [
                {
                    'name': '轮播管理',
                    # 'icon': 'fa fa-th-list',
                    'url': 'web/carousel/'
                },
                {
                    'name': '喇叭公告',
                    # 'icon': 'fa fa-th-list',
                    'url': 'web/noticebar/'
                },
                {
                    'name': '发音类型',
                    # 'icon': 'fa fa-th-list',
                    'url': 'web/fayintypemodel/'
                },
                {
                    'name': '主领域管理',
                    'icon': 'fa fa-th-list',
                    'url': 'web/lingyu/'
                },
                {
                    'name': '子领域管理',
                    'icon': 'fas fa-ellipsis-h',
                    'url': 'web/sublingyu/'
                },
                {
                    'name': '词条收藏',
                    'icon': 'fa fa-heartbeat',
                    'url': 'web/myfavoritad/'
                },
                {
                    'name': '子领域收藏',
                    'icon': 'fa fa-heartbeat',
                    'url': 'web/myfavoritcat/'
                },
                {
                    'name': '卡片学习',
                    'icon': 'fa fa-vr-cardboard',
                    'url': 'web/usercardhistory/'
                },
                {
                    'name': '用户错题',
                    'icon': 'fa fa-heartbeat',
                    'url': 'web/mistakemodel/'
                },
                {
                    'name': '听音练习',
                    # 'icon': 'fa fa-heartbeat',
                    'url': 'web/listenpracticemodel/'
                },
                {
                    'name': '知识库分类',
                    # 'icon': 'fa fa-heartbeat',
                    'url': 'web/knowledgetypemodel/'
                },
                {
                    'name': '知识文案',
                    # 'icon': 'fa fa-heartbeat',
                    'url': 'web/articlemodel/'
                },
                {
                    'name': '词条管理',
                    'icon': 'fa fa-folder',
                    'url': 'web/ctitem/'
                },
                {
                    'name': '帖子类型',
                    'icon': 'fa fa-folder',
                    'url': 'web/topictypemodel/'
                },
                {
                    'name': '社区帖子',
                    'icon': 'fa fa-folder',
                    'url': 'web/topicmodel/'
                },
                {
                    'name': '帖子图片',
                    'icon': 'fa fa-folder',
                    'url': 'web/topicimgs/'
                },
                {
                    'name': '帖子评论',
                    'icon': 'fa fa-folder',
                    'url': 'web/topiccomment/'
                },
                {
                    'name': '用户反馈',
                    'icon': 'fas fa-comment',
                    'url': 'web/comments/'
                },
            ]
        }
    ]
}

APP_ID = "wx7a3fc12c48af5f9d"
APP_KEY = "4abc0b6c34f39233c32948bf3e39cd22"

WECHAT_PAY = {
    'APPID': 'wx7a3fc12c48af5f9d',
    'APPSECRET': '4abc0b6c34f39233c32948bf3e39cd22',
    'MCHID': '1666095007',
    'API_V3_KEY': 'qazwsxedcrfvtgbyhnujmikolpqazwsx',

    'CERT_SERIAL': '4FBFE7E2C5B3751E6090642478994A02A5DFDB96',
    'NOTIFY_URL': 'http://aly.jsxinlingdi.com:7001/user/pay/notify/' if platform.system() in ["Windows",
                                                                                              "Darwin"] else 'https://siyu.jsxinlingdi.com/user/pay/notify/',
    # 支付结果回调地址
    "CERT_PATH": str(BASE_DIR / "certs/apiclient_cert.pem"),  # 证书路径
    "KEY_PATH": str(BASE_DIR / "certs/apiclient_key.pem"),  # 私钥路径
    "PUB_KEY_PATH": str(BASE_DIR / "certs/pub_key.pem"),  # 微信支付公钥路径
    "CERT_DIR": str(BASE_DIR / "certs")
}

SHOWSQ = False
ALLCAN = False

# SHOWSQ = True
# ALLCAN = True


# ElevenLabs 配置
ELEVEN_LABS_API_KEY = "sk_8eba9500b80032b24197a7a0b925a9f2d30425969737c294"
# 推荐模型：多语言 v2 (支持斯瓦希里语)
ELEVEN_LABS_MODEL_ID = "eleven_multilingual_v2"
# 推荐声音 ID (这里用的是 Rachel 的 ID，建议换成你喜欢的非洲口音 ID)
ELEVEN_LABS_VOICE_ID = "FbFkkfp4Iv6U5Q1WC4C2"