# Generated by Django 4.0.1 on 2025-11-20 08:59

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userrole',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
