# Generated by Django 4.0.1 on 2025-11-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_alter_userrole_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jifen',
            field=models.IntegerField(default=30, verbose_name='我的积分'),
        ),
    ]
