# Generated by Django 4.0.1 on 2025-11-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_userprofile_jifen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='portrait',
            new_name='avatarUrl',
        ),
    ]
