# Generated by Django 4.0.1 on 2025-11-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_rename_portrait_userprofile_avatarurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='jifen',
            new_name='points',
        ),
    ]
