# Generated by Django 4.0.1 on 2025-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_rename_jifen_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isRecorder',
            field=models.BooleanField(default=False, verbose_name='是否可以录音'),
        ),
    ]
