# Generated by Django 4.0.1 on 2025-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_userprofile_isrecorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='studyTime',
            field=models.BigIntegerField(default=0, verbose_name='学习时间/秒'),
        ),
    ]
