# Generated by Django 4.0.1 on 2025-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_userprofile_studytime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='studyTime',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totalStudyTime',
            field=models.BigIntegerField(default=0, verbose_name='学习时间/秒'),
        ),
    ]
