# Generated by Django 4.0.1 on 2025-12-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_remove_userprofile_studytime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
