# Generated by Django 4.0.1 on 2025-12-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=30, verbose_name='积分'),
        ),
    ]
