# Generated by Django 4.0.1 on 2025-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_alter_userprofile_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuiYuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格数值')),
            ],
            options={
                'verbose_name': '会员类型',
                'verbose_name_plural': '会员类型',
            },
        ),
    ]
