# Generated by Django 4.0.1 on 2025-12-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0011_huiyuanmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuiYuanModel',
        ),
    ]
