# Generated by Django 4.0.1 on 2025-12-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_delete_huiyuanmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuiYuanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格数值')),
            ],
            options={
                'verbose_name': '会员类型',
                'verbose_name_plural': '会员类型',
            },
        ),
        migrations.CreateModel(
            name='HuiYuanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isExpired', models.BooleanField(default=False, verbose_name='是否过期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typehuiyuan', to='myuser.huiyuantype', verbose_name='会员类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userhuiyuan', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员记录',
                'verbose_name_plural': '会员记录',
            },
        ),
    ]
