# Generated by Django 4.0.1 on 2025-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0014_transcationmanage_delete_huiyuanrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huiyuantype',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='huiyuantype',
            name='avgText',
            field=models.CharField(default='', max_length=32, verbose_name='均价'),
        ),
    ]
