# Generated by Django 4.0.1 on 2025-12-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0015_rename_title_huiyuantype_name_huiyuantype_avgtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isvip',
            field=models.BooleanField(default=False, verbose_name='是否VIP'),
        ),
    ]
