# Generated by Django 4.0.1 on 2025-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0016_remove_userprofile_points_userprofile_isvip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuiYuanType',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=30, verbose_name='积分'),
        ),
    ]
