# Generated by Django 4.0.1 on 2025-12-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0017_delete_huiyuantype_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=50, verbose_name='积分'),
        ),
    ]
