# Generated by Django 4.0.1 on 2025-12-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0018_alter_userprofile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isvip',
        ),
    ]
