# Generated by Django 4.0.1 on 2025-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0019_remove_userprofile_isvip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuiYuanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格数值')),
                ('avgText', models.CharField(default='', max_length=32, verbose_name='均价')),
            ],
            options={
                'verbose_name': '会员类型',
                'verbose_name_plural': '会员类型',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isvip',
            field=models.BooleanField(default=False, verbose_name='是否VIP'),
        ),
    ]
