# Generated by Django 4.0.1 on 2025-12-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0020_huiyuantype_userprofile_isvip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huiyuantype',
            name='avgText',
        ),
    ]
