# Generated by Django 4.0.1 on 2025-12-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0021_remove_huiyuantype_avgtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='huiyuantype',
            name='points',
            field=models.IntegerField(default=0, verbose_name='点数'),
        ),
    ]
