# Generated by Django 4.0.1 on 2025-12-16 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0022_huiyuantype_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userscore', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '做题得分 ',
                'verbose_name_plural': '做题得分 ',
            },
        ),
    ]
