# Generated by Django 4.0.1 on 2025-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0023_scorerecordmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecordmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
