# Generated by Django 4.0.1 on 2025-12-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0024_alter_scorerecordmodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=200, verbose_name='积分'),
        ),
    ]
