# Generated by Django 4.0.1 on 2025-12-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0025_alter_userprofile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=500, verbose_name='积分'),
        ),
    ]
