# Generated by Django 4.0.1 on 2025-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0027_alter_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='luyinpindao',
            field=models.CharField(blank=True, default='', help_text='空、2、3', max_length=2, null=True, verbose_name='录音频道'),
        ),
    ]
