# Generated by Django 4.0.1 on 2025-12-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0028_userprofile_luyinpindao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=500, verbose_name='积分'),
        ),
    ]
