# Generated by Django 4.0.1 on 2025-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0029_alter_userprofile_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huiyuantype',
            options={'verbose_name': '购买套餐', 'verbose_name_plural': '购买套餐'},
        ),
        migrations.AddField(
            model_name='huiyuantype',
            name='color',
            field=models.CharField(default='', max_length=8, verbose_name='按键颜色'),
        ),
    ]
