# Generated by Django 4.0.1 on 2025-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0030_alter_huiyuantype_options_huiyuantype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=200, verbose_name='积分'),
        ),
    ]
