# Generated by Django 4.0.1 on 2025-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0031_alter_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerecordmodel',
            name='type',
            field=models.CharField(choices=[('0', '做题练习'), ('1', '听音组句')], default=0, max_length=1, verbose_name='分数类型'),
        ),
    ]
