# Generated by Django 4.0.1 on 2025-12-28 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0033_userloginrecordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginrecordmodel',
            name='login_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='登录日期'),
            preserve_default=False,
        ),
    ]
