# Generated by Django 4.0.1 on 2025-12-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0034_userloginrecordmodel_login_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginRecordModel',
        ),
    ]
